name: Trigger auto deployment for hb-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/admin/**'
      - 'packages/shared/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/hb-frontend-AutoDeployTrigger-708c640b-934c-4a77-af6c-f0d90962e0ad.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HBFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HBFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HBFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: apps/admin/Dockerfile
          registryUrl: ${{ secrets.HBFRONTEND_REGISTRY_URL }}
          registryUsername: ${{ secrets.HBFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HBFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: hb-frontend
          resourceGroup: rg1-hb1-b2b-dev
          imageToBuild: ${{ secrets.HBFRONTEND_REGISTRY_URL }}/hb-frontend:${{ github.sha }}
          buildArguments: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_WEB_DOMAIN=${{ secrets.NEXT_PUBLIC_WEB_DOMAIN }}
            NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
